name: articles_app_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.9
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  mockito: ^5.4.4
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  http: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.8.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  output_dir: "lib/l10n/generated/"
  arb_dir: "lib/l10n/"
  untranslated-messages-file: lib/l10n/l10n_errors.txt